const genshinData = [
    { name: " Zhongli", element: "Geo", weapon: "Polearm", info: "Wangsheng Funeral Parlor's mysterious consultant. Handsome, elegant, and surpassingly learned. Though no one knows where Zhongli is from, he is a master of courtesy and rules. From his seat at Wangsheng Funeral Parlor, he performs all manner of rituals. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/c/c2/Character_Zhongli_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/e699d7e2413ed5dfb384ee48c2b872d3_2081056854784197634.png" },

    { name: " Diluc", element: "Pyro", weapon: "Claymore", info: "As the wealthiest gentleman in Mondstadt, the ever-dapper Diluc always presents himself as the epitome of perfection. But behind the courteous visage burns a zealous soul that has sworn to protect Mondstadt at all costs, allowing him to mercilessly vanquish all who threaten his city. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/0/02/Character_Diluc_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/f5ae62eff2cf426e98626c882dd0cf0d_3240767163310397909.png" },

    { name: " Fischl", element: "Electro", weapon: "Bow", info: "A mysterious girl who calls herself \Prinzessin der Verurteilung\ and travels with a night raven named Oz. Currently serves as an investigator in the Adventurers' Guild. Through her unique abilities, eccentric character, and (while she would never admit it herself) hard work, Fischl has become a rising star among the Adventurers' Guild's investigators, earning the recognition of all. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/1/14/Character_Fischl_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/96297a7f2679bf0dce4fb9d11120b882_6701280931940281887.png" },

    { name: " Xiao", element: "Anemo", weapon: "Spear", info:  "One of the mighty and illuminated adepti guarding Liyue, also heralded as the \ Vigilant Yaksha. \ Despite his youthful appearance, tales of his exploits have been documented for millennia. He is especially fond of Wangshu Inn's Almond Tofu. This is because it tastes just like the sweet dreams he used to devour. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/b/b9/Character_Xiao_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/930f3ce55517e3c711a962c82e4639c0_8691377287489555826.png" },

    { name: "Raiden Shogun", element: "Electro", weapon: "Spear", info: "The Raiden Shogun is the awesome and terrible power of thunder incarnate, the exalted ruler of the Inazuma Shogunate. With the might of lightning at her disposal, she commits herself to the solitary pursuit of eternity. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/5/52/Character_Raiden_Shogun_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/fdcbc9ef8859b7077d92ae38d925e15e_4430297517104014075.png" },

    { name: "Traveler", element: "All", weapon: "Sword", info: "The Traveler is the playable protagonist of Genshin Impact. In the opening cutscene, twin siblings from another world travel through the universe, until an unknown god blocks their path. The player gets to choose either Aether (male) or Lumine (female) as the traveler and Traveler's Sibling gets captured. Their power to travel is sealed, leaving them stranded on Teyvat. They save Paimon by fishing her out of the water and she accompanies them as their new travel companion. Together they set out on a journey to find The Seven and reunite with the Traveler's lost sibling. -Description from the Genshin Impact Wiki", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/7/71/Character_Traveler_Thumb.png/", image: "https://static.wikia.nocookie.net/gensin-impact/images/2/29/Traveler_Card.png/" },

    { name: "Amber", element: "Pyro", weapon: "Bow", info: "A perky, straightforward girl, who is also the only Outrider of the Knights of Favonius. Her amazing mastery of the glider has made her a three-time winner of the Gliding Championship in Mondstadt. As a rising star within the Knights of Favonius, Amber is always ready for any challenging tasks. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/c/c6/Character_Amber_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/6f0ef40157e95b0d59455c12f4d3f270_6966278935690800707.png" },

    { name: "Noelle", element: "Geo", weapon: "Claymore", info: "Like most of Mondstadt's young people, Noelle always dreamed of being a knight of Favonius when she grew up. She may not have what it takes to be a knight just yet, but she is learning. Working as a maid at the Knights' headquarters, she is constantly taking notes on what constitutes knightly speech, knightly conduct, and knightly customs. She holds firm to her belief that one day she will join their ranks — she just needs to keep trying her hardest at everything she does. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/a/ab/Character_Noelle_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/c8a5da498d29faa1c8f2e2bfb60efbd5_4363852007421467828.png" },

    { name: "Kaeya", element: "Cryo", weapon: "Sword", info: "In the Knights of Favonius, Kaeya is the most trusted aide for the Acting Grand Master Jean. You can always count on him to solve any intractable problems. Everyone in Mondstadt loves Kaeya, but no one knows what secrets this witty, charming knight has... —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/3/33/Character_Kaeya_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/cbce61ef1ee5586c4e77b2070348685f_2003673786618101140.png" },

    { name: "Lisa", element: "Electro", weapon: "Catalyst", info: "She is an intellectual witch who can never get enough naps. As the Librarian of the Knights of Favonius, Lisa is smart in that she always knows exactly what to do with whatever troubles her. As much as she loves her sleep, she still manages to keep everything under control in a calm, composed manner. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/5/51/Character_Lisa_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/43922f5162840c215638affedad0459a_3369229991804918602.png" },

    { name: "Barbara", element: "Hydro", weapon: "Catalyst", info: "The Deaconess of the Favonius Church and a shining starlet adored by all. Although the concept of a starlet is rather novel in a city of bards, the people of Mondstadt love Barbara nonetheless. \ I owe everything to the city's spirit of freedom \ — Barbara, regarding her popularity. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/7/72/Character_Barbara_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/6c009f0631eb71e697c2da76b608a51e_679009763713991286.png" },

    { name: "Xiangling", element: "Pyro", weapon: "Spear", info: "The Head Chef at the Wanmin Restaurant and also a waitress there, Xiangling is extremely passionate about cooking and excels at her signature hot and spicy dishes. Though still young, Xiangling is a true master of the culinary arts with all the skills of a kitchen veteran. She enjoys a good reputation among the hearty eaters at Chihu Rock. There's absolutely no need to be nervous if she wants you to sample her latest creation. It will not disappoint. Promise. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/a/a0/Character_Xiangling_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/1169862f9fa35734b06ce09c96dad9ae_3683516363976115873.png" },

    { name: "Collei", element: "Dendro", weapon: "Bow", info: "A Trainee Forest Ranger who is under the tutelage of Tighnari. She started her academic career a little later thatn her peers, so she is currently working hard to catch up. She hides the other side of her personality deep under the surface of optimism and kindness. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/9/9e/Character_Collei_Thumb.png/", image: "https://static.wikia.nocookie.net/gensin-impact/images/2/2a/Character_Collei_Full_Wish.png/" },

    { name: "Tartaglia", element: "Hydro", weapon: "Bow", info: "Meet Tartaglia — the cunning Snezhnayan whose unpredictable personality keeps people guessing his every move. Don't be under any illusion as to what he might be thinking or what his intentions are. Just remember this: Behind that innocent, childlike exterior lies a finely honed instrument of war. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/5/53/Character_Tartaglia_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/uploadstatic/contentweb/20201103/2020110321160453386.png" },

    { name: "Kamisato Ayato", element: "Hydro", weapon: "Sword", info: 'Current head of the Kamisato Clan and, accordingly, the Yashiro Commissioner. He always has a way of attaining his purpose in a well-thought-out manner. However, few people understand what that "goal" he holds most dear is.  —Description from the Official Website', portrait: "https://static.wikia.nocookie.net/gensin-impact/images/a/a2/Character_Kamisato_Ayato_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/037d6fa79d3066c5bc8711187ad2f673_8716208043389620011.png" },

    { name: "Sangonomiya Kokomi", element: "Hydro", weapon: "Catalyst", info: "Kokomi is the Divine Priestess of Watatsumi Island, and also serves as its supreme leader. She is well-versed in the art of war, is good at strategizing, and has keen insights into military affairs. She is also adept at handling domestic affairs, diplomacy, and other matters. Still, this unfathomable leader has a mysterious side to her...  —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/c/cc/Character_Sangonomiya_Kokomi_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/8ca5953fb331d71bc880496f5e8b7745_3256211802655370131.png" },

    { name: "Thoma", element: "Pryo", weapon: "Polearm", info: "The housekeeper of the Yashiro Commission's Kamisato Clan, and a well-known 'fixer' in Inazuma. Friendly and approachable, Thoma fits in with the crowd easily wherever he is. At first glance, he seems to be a very easygoing person, but he is in fact very responsible. He has an extraordinarily serious side, be it in his work or his interpersonal communications. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/8/8a/Character_Thoma_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/9d753f7cee1ed5c645340d6396c50c46_5113716789151737645.png" },

    { name: "Ningguang", element: "Geo", weapon: "Catalyst", info:'Owner of the Jade Chamber in the skies above Liyue, there are stories abound about Ningguang, with her elegance and mysterious smile.As a Tianquan of the Liyue Qixing, not only does she embody law and order, she also represents fortune and wit. —Description from the Official Website[1]', portrait: "https://static.wikia.nocookie.net/gensin-impact/images/2/2b/Character_Ningguang_Thumb.png/", image: "https://static.wikia.nocookie.net/gensin-impact/images/3/3a/Character_Ningguang_Full_Wish.png/" },

    { name: "Kaedehara Kazuha", element: "Geo", weapon: "Sword", info: 'A wandering samurai from Inazuma with a modest and gentle personality. Beneath a youthful and carefree demeanor lies a heart that hides a great many burdens from the past. Seemingly easygoing, Kazuha has his own code of conduct. —Description from the Official Website', portrait: "https://static.wikia.nocookie.net/gensin-impact/images/f/f0/Character_Kaedehara_Kazuha_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/44e2d916d9c13bca863d56423004fd98_6715584262683208581.png" },

    { name: "Venti", element: "Anemo", weapon: "Bow", info: "A bard that seems to have arrived on some unknown wind — sometimes sings songs as old as the hills, and other times sings poems fresh and new. Likes apples and lively places but is not a fan of cheese or anything sticky. When using his Anemo power to control the wind, it often appears as feathers, as he's fond of that which appears light and breezy. —Description from the Official Website", portrait: "https://static.wikia.nocookie.net/gensin-impact/images/8/8d/Character_Venti_Thumb.png/", image: "https://webstatic.hoyoverse.com/upload/contentweb/2022/07/22/965e940e6caafe8fbd4bf0e17653000b_4508958090491775485.png" }
];

module.exports = genshinData;